### ISSUE TITLE
Error in fnc_OPCOM.sqf

### ISSUE THREAD

**Issue by shukari** [ALiVEOS/ALiVE.OS#123]
Get this error on server very often:

```
18:40:08 Error in expression <,_pos] call ALiVE_fnc_OPCOM};
} foreach _profiles;
};
};
};>
18:40:08   Error position: <_profiles;
};
};
};>
18:40:08   Error Undefined variable in expression: _profiles
18:41:01 Error in expression <et;


_profileIDs = [];
{
_profileIDs = _profileIDs + ([ALIVE_profileHandler, "g>
18:41:01   Error position: <_profileIDs + ([ALIVE_profileHandler, "g>
18:41:01   Error Undefined variable in expression: _profileids
18:41:01 File x\alive\addons\mil_opcom\fnc_OPCOM.sqf, line 462
18:41:01 Error in expression <"_pos"];

_profiles = [];
{
_profiles = _profiles + ([ALiVE_ProfileHandler,"getP>
18:41:01   Error position: <_profiles + ([ALiVE_ProfileHandler,"getP>
18:41:01   Error Undefined variable in expression: _profiles
18:41:01 Error in expression <,_pos] call ALiVE_fnc_OPCOM};
} foreach _profiles;
};
};
};>
18:41:01   Error position: <_profiles;
};
};
};>
18:41:01   Error Undefined variable in expression: _profiles
18:41:01 Error in expression <ime;

_profileIDs = [];
{
_profileIDs = _profileIDs + ([ALIVE_profileHandler, "g>
18:41:01   Error position: <_profileIDs + ([ALIVE_profileHandler, "g>
18:41:01   Error Undefined variable in expression: _profileids
18:41:01 File x\alive\addons\mil_opcom\fnc_OPCOM.sqf, line 2288
```

**Comment by shukari** [comment]
i have a mission... but it use mods...

**Comment by tupolov** [comment]
If you remove your mods do you get the same issue?

**Comment by shukari** [comment]
http://pastebin.com/AB0MmPS8
Here the server rpt... i will try it later...

**Comment by shukari** [comment]
ok, after >2h testing... a mission with my modset (@3den Enhanced;@ace;@ACEX;@ALiVE;@AresModAchillesExpansion;@CBA_A3;@sthud;@task_force_radio;@ASR_AI3;@athena;) and ONLY alive modules nor error... but if i have my common ace and tfar modules this error appears...

**Comment by shukari** [comment]
Ok, here the repo mission mods only cba and alive -> http://workupload.com/file/ZzMX2qf
and here the rpt -> http://pastebin.com/TDhMivYP

**Comment by tupolov** [comment]
Thanks. Will test today

**Comment by tupolov** [comment]
From what I can see you have specified factions in OPCOM where there are no forces to control. 

For example you have OPCOM for BLU_F, BLU_T_F and BLU_CTRG_F but only place BLU_F forces. You either need to place the other factions or remove them from OPCOM. Same with your OPFOR OPCOM.

Also for MIL Placement, on Altis you should filter small objectives. Both MIL placement modules are set to Do Not Filter. This is not recommended on Altis due to its size and perf impact.

Saying all this, we should not get an error due to some factions not being present. We will make the code more robust here.
