### ISSUE TITLE
FIA Opfor Spawn at Roadblocks with Non-Vanilla factions

### ISSUE THREAD

**Issue by AUTigerGrad** [ALiVEOS/ALiVE.OS#193]
When using CDF from CUP, SLA from CUP, and US Army from CUP, FIA Opfor spawn at all roadblocks instead of the proper faction.

I have reproduced this multiple times with all of the CUP factions.

Vanilla units spawn correctly.

**Comment by HeroesandvillainsOS** [comment]
I've seen this with factions other than CUP, FWIW. Including Massi, RHS, Project OPFOR and ORBAT as well.

@AuTigerGrad, I'd assume a rpt would be useful. Probably with the placement module and/or Virtual AI debugged but a dev would need to confirm for sure.

**Comment by coachwn** [comment]
Yeah its not just CUP but it seems to be more prevalent with that faction.

**Comment by tupolov** [comment]
This isn't faction related. This is more to do with how the roadblock code chooses a faction.

```
_fac = [_pos, _radius] call ALiVE_fnc_getDominantFaction;

if (isNil "_fac") then {
    _fac = "OPF_G_F";
};
```
Basically its not finding a dominant faction in the area, so defaulting to OFP_G_F. Not optimal!

**Comment by friznit** [comment]
Need to figure out a better / alternative solution.  TBD.

**Comment by HeroesandvillainsOS** [comment]
I like number 1. The dominant faction mechanic staying true means more to me than shooting something for the pure sake of it. And I'm ok with the occasional empty roadblock.

**Comment by coachwn** [comment]
I would prefer #2 then #3 as a random aspect.

**Comment by HeroesandvillainsOS** [comment]
I can't imagine number 2 would go over very well with most players. Imagine having vanilla 2035 factions spawning in Vietnam or as insurgent forces in Afghanistan. I mean it would basically make this bug report an official feature.

Players can already make three way battles with two different factions organically as it is. I mean, if units absolutely had to spawn, 3 is much more ideal than 2 IMO because it would at least be true to the immersion. But I definitely respect your opinion on it coachwn and it's really neat that they're looking for opinions on this.

**Comment by coachwn** [comment]
Crap I meant #1 & #3.....my phone typing skills suck.

**Comment by HeroesandvillainsOS** [comment]
Even with 1.2.7 increasing the radius for dominant faction searching from 100m to 300m, I just saw a vanilla OPFOR faction spawn at a roadblock in a mission that's supposed to be IND vs BLU only. I guess I'm just saying, this ticket is still very much needed.
