### ISSUE TITLE
Enhancements to Civ Spawns

### ISSUE THREAD

**Issue by friznit** [ALiVEOS/ALiVE.OS#205]
Reports of no or too few civs spawning on some maps.  Need to verify Civ Pop is working as intended and providing the right effect both alone and in the context of Asymmetric (where more civs are required).

Options are:

~User error: Civ Pop module hard limit set to default 25 and map wide TAOR so that civ profiles are too thin on the ground~

~Module bug:  initial spawn of civs is fine but thereafter they stop spawning.  Test by moving around the map.~

- Bad index: insufficient buildings set to spawn civs during indexing.  Is the indexing tool clear enough on how to do this?
  - Possible issues with a number of maps indexed more recently due to confusion over Civ Population Building (enterable buildings for spawning civ pop) and Civ Settlement Building Type (major buildings that signpost civ settlements)

**Comment by nateberkopec** [comment]
I've definitely seen this, but concede it could have been user error (because we eventually got it working).

**Comment by HeroesandvillainsOS** [comment]
The most obvious example of there being some kind of issue not user related would be Diyala. From what I gather, a lot of those buildings are JBad. Maybe JBad is somehow related to the issue at hand? 

@Friznit, what are some other examples of maps with civ problems? I know Kunduz and Isla Duala have had some reports, but both maps are listed as needing reindexing.

**Comment by nateberkopec** [comment]
If it helps, we were having issues with civ spawn on Tanoa.

**Comment by tupolov** [comment]
I think the only issue with indexing is to make sure that enterable buildings have been marked as civ buildings. I believe there are 2 options for civ buildings and only one is used for civ ambience.

**Comment by wolffy-au** [comment]
Tested on Agia Marina
Extreme settings 84 units
High ~30
Med ~ 21
Low ~ 10
Commit https://github.com/ALiVEOS/ALiVE.OS/commit/c8d99e5706ae2c1e5bf7760d8ad686fe930d812b

Remains issue around 1 group per civilian. Don't close the ticket yet.

**Comment by friznit** [comment]
Check indexes that Civ Pop Building Types are available and not all in Civ Settlement Building Type (action on Friz)

**Comment by HeroesandvillainsOS** [comment]
"User error: Civ Pop module hard limit set to default 25 and map wide TAOR so that civ profiles are too thin on the ground"

I see you crossed this out. Let's back up a sec because I'm one of those reporting issues on some maps and civ spawns. If you leave it at the default 25, and make the whole map a TAOR, I thought the way it worked was on 25, it would only spawn 25 civs in the game world around the player (for performance purposes), and NOT as the map is only able to have 25 civs, including virtual ones no where near the player.

Can someone clarify? I'm pretty positive when left on 25 the map will have way more than 25 civs in total. It's just not more than 25 real ones in game world spawned directly around the player.

Am I right on that or no?

**Comment by SpyderBlack723** [comment]
Active limiters only control how many units can be spawned at one time, not how many are created at mission start.

**Comment by HeroesandvillainsOS** [comment]
Thanks that makes sense because obviously we have the low/medium/high/extreme options for overall density. I just saw the crossed out part about him mentioning user error and wanted to make sure we are all on the same page (seeing as I'm one of the people noticing odd civ spawning behavior on some maps).

Thanks for clarifying.
