### ISSUE TITLE
[amb_civ] Add ambient Civ crowds

### ISSUE THREAD

**Issue by tupolov** [ALiVEOS/ALiVE.OS#226]
Crowds are different to individual ambient civs in that they are single groups of civ that will congregate in towns, villages around key buildings, markets or public areas. 

The crowds will spawn at a smaller radius when players are in towns. Spawned in large buildings, groups move as one to a single or multiple key positions.

Ambient crowd noise follows the crowd.

Crowd can be dispersed with the use of loudspeakers or gun shots.

Crowd individuals will despawn or disperse to enterable buildings where they will despawn.

Crowds can appear in order to protest or support players. Crowds can also appear at certain periods of the day at specific locations I.e markets, mosques, town hall etc

**Comment by Vegas** [comment]
BUMP.

Ambient civilians add a lot of realism to campaigns/operations.

As is stands, it is somewhat difficult to correctly simulate crowd behavior with the current system. Right now, civilians are assigned starting positions (houses/buildings via index tool "allow civilians to spawn here"), from which they then get random waypoints to have them move around.

This is a great system for when players breach to clear buildings to find civilians inside, but the streets still seem too empty for it to be realistic.

I have a few suggestions for this outstanding idea:
- Modify the current civilian spawn system so that civilians will spawn inside houses and remain very close to their homes, or split the system to force a few to stay inside the houses. This would help create a more seamless transition during the crowd's "despawn" feature when they enter homes because if players followed the crowd inside, there would still be some dudes hanging out inside.
- Next, I would create Tupolov's suggested crowd simulation to populate other areas. Because features.
- Lastly, SpyderBlack has a wonderful addon set with "ambience", which spawns civilian traffic driving all over the place. I would love to see this feature expanded upon within ALiVE. It would be great to have civilian cars actually driving from town to town.
- One last suggestion, please add **goats** and other animal herds to ALiVE. It would be such an Arma 2 memory trip to see goat/other animal herds around the towns with civilians leading them around.

**Comment by HeroesandvillainsOS** [comment]
@Vegas Spyder Addons adds ambient goats and yeah, it's amazing.

**Comment by tupolov** [comment]
Done!
