### ISSUE TITLE
Issues with patrols & civilians on Kalu Khan

### ISSUE THREAD

**Issue by Knight1981** [ALiVEOS/ALiVE.OS#298]
At the moment we using CBA 3.1.2.161105 and ALIVE 1.2.9.1701291.

We have the problem that the military placement module doesn't spawn any infantry patrols (only camps and CQB) on Kalu Khan. Furthermore the Civilian Placement module doesn't spawn any Civilians on this map. We have no filter set (like tiny objects, small objects etc. Value is set to "no filter"). I've also tried different supported factions.

2nd problem: If I install the latest CBA version 3.2.0 all our maps with ALIVE modules doesn't load anymore :( I've tried also latest ALIVE version 1.3.0.1702201.

**Comment by friznit** [comment]
Kalu Khan index has been broken since its last update.  See here: https://github.com/ALiVEOS/ALiVE.OS/issues/9

Latest release version of CBA broke ALiVE.  There's a fix available in the dev version: https://forums.bistudio.com/topic/187954-alive-advanced-light-infantry-virtual-environment-10-ga/?do=findComment&comment=3157123

**Comment by Knight1981** [comment]
Thank you for the answer. hope the Kalu Khan map author will fix it.

BUT as I can see we have problems in all our maps (also Tanoa, Altis, Stratis) with the random patrols. Civilians, CQB and Camps is spawning correctly but no random patrols around the players with CBA 3.1.2.161105.

**Comment by Knight1981** [comment]
Hey friznit,

I have got a response from makhno, the map author of Kalu Khan and N'Ziwasogo. He is willing to solve that issue but he needs more information. His answer:

"Just config error is not nearly enough. If you can provide me with a meaningfull error message, I may have a chance to fix it [...] All my maps are based on the same structure/config on a very indistrialised way.
So any error would probably happen on all of them."

Maybe you could give me / him a bit more information what exactly the problem is. He isn't using Alive and do not know what the problem is and what needs to be changed in the map configuration.

For us Alive is not usable on this maps because of two main reasons:
1.) Alive tooks too much time for loading on these maps (Kalu Khan > 15 Min, N'Ziwasogo about 40 minutes). Without Alive modules the maps are loading in less than 4 min! I already filtered to "ignore low and medium objects", it doesn't improve the loading time.
2.) No Civilians are spawning

It would be really helpful if you could provide some detailled information what he has to fix to make these maps loading much faster and supporting the civilian modules. Thanks a lot!

**Comment by highhead** [comment]
Hi!

For us Alive is not usable on this maps because of two main reasons:
1.) Alive tooks too much time for loading on these maps (Kalu Khan > 15 Min, N'Ziwasogo about 40 minutes). Without Alive modules the maps are loading in less than 4 min! I already filtered to "ignore low and medium objects", it doesn't improve the loading time.

--> Init was broken since some A3 patches, postinit kicked in too late, which made the server take ages to init. This should be fixed in the upcoming release! You can test init in SP with latest ALiVE RC (https://github.com/ALiVEOS/ALiVE.OS/releases/tag/v1.3.0.1702201)

2.) No Civilians / vehicles are spawning

--> Should be fixed with re-index of current Kalu Khan version. It is important, that civilian buildings are defined for ALiVE to disconver the correct buildings!

**Comment by Knight1981** [comment]
1.) Great news! Hope that the new version will released very soon :) Thank you!

2.) Who is able to re-index these maps (Kalu Khan, N'Ziwasogo)? Alive team as well or only the map author?

**Comment by friznit** [comment]
Fixed in dev.

**Comment by Knight1981** [comment]
thank you so much. Can't wait for the release :)

**Comment by Knight1981** [comment]
We have tested the new version and it works really good.

Kalu Khan is now loading in about 3 min (instead of > 15 min), N'Ziwasogo in about 5:30 (instead of > 40 min). Civilians Module works also on Kalu Khan now. :)
