### ISSUE TITLE
Profiles spawned by objective modules causing sharp and sudden drops in FPS in SP

### ISSUE THREAD

**Issue by HeroesandvillainsOS** [ALiVEOS/ALiVE.OS#350]
On some maps, obj module profile spawns are causing sharp drops in performance. To repro:

1. Place a playable unit down on Altis in the SP editor.
2. Place ALiVE Required, Virtual AI, two OPCOM modules (one BLU_F and one OPF_F) and two CIV obj modules (one for each commander), filtering out small and medium size objectives.
3. Sync the obj modules to both commanders (this will create around 134 objectives on init)
4. Press preview scenario (then open the tablet and ghost if you're worried about being killed)
5. Wait 5-7 minutes for ALiVE to fully initialize.
6. Start jogging in a straight line.

Every few seconds, you will see drastic and sudden drops in FPS. On other maps, such as Chernarus, this issue is much more apparent and frequent. I only see this problem on certain maps (so far Altis, Chernarus, Diyala).

Altis test: https://www.dropbox.com/s/q76ahk7hatlusgb/Stutter_test.Altis.zip?dl=0
Chernarus (requires CUP Maps and CUP Core): https://www.dropbox.com/s/yojr1izw144g2h0/Stutter_test.Chernarus.zip?dl=0

**Comment by highhead** [comment]
the mission given, shows 2 main things in regards to performance:

- Too many profiles passed to virtual combat (115 in my test) causes a short freeze every few seconds until the troops where dead and the amount normalizes --> fixed

- There is a bug in OPCOMs "resetOrders"-operation since maybe forever (at least since over a year) which caused a freeze everytime an objective was reserved, if there were too many objectives and profiles passed. --> fixed

Mind that while this mission showed that issues perfectly, the usage of placement modules like in the mission given (2 placement modules without TAORs for two opposing sides directly) is unintended and unsupported. please use TAORs to define different placement perimeters for the selected opposing forces.

**Comment by HeroesandvillainsOS** [comment]
Thanks @highhead and also thank you for the module usage tips as well. I appreciate it man.
