### ISSUE TITLE
Possible BUG: AI civilians and troops never re-virtualize and ambient vehicles do not despawn

### ISSUE THREAD

**Issue by coachwn** [ALiVEOS/ALiVE.OS#364]
As referenced in this post here we are seeing AI civilians and troops just roaming around and not disappearing when the players have moved out of the area. If the civilians and troops do despawn the vehicles are still showing up on the map and I am wondering if it is causing the fps drops we are seeing on the server. Is anyone else having this happen?

[https://github.com/Spearhead-Gaming-Milsim/Operation-Wildfire/issues/24](url)

Granted we are using a ton of mods on this mission but they are all mods that have been used with ALiVE in the past without this same issue appearing.

Also wondering if this issue could be tied into the Spyder Addons aspect with vehicles? Going to disable the vehicles in that on my test box and see what happens.

**Comment by friznit** [comment]
Unable to repro.  On a large, mod heavy game with 40+ players, Alive profiles were spawning/despawning as expected.  Due to "smooth spawn" mechanic, it can take several minutes on heavily populated areas for the spawning/despawning to complete.

Also note that the Zeus camera and Headless Clients and will spawn profiles, so ensure they are kept out of the way.

**Comment by coachwn** [comment]
Haven't had a chance to make a repro on this but will be working on it over the next few days. I was having this issue after eliminating the vehicles from the ALiVE modules and only having them spawning in via Spyder Addons so it may not be an ALiVE issue. As I said going to verify and if that proves to be the case will send to Spyder as needed.

**Comment by SpyderBlack723** [comment]
Reopen if needed
