### ISSUE TITLE
Error fnc_createRoadblock (ALiVE Dev)

### ISSUE THREAD

**Issue by friznit** [ALiVEOS/ALiVE.OS#480]
### Prerequisites

* [x] Can you reproduce the problem using ALiVE and CBA Only?
* [x] Are you running the latest version of ALiVE ?  (Latest Dev from Git)
* [x] Are you running the latest version of CBA_A3?
* [x] Have you attached an unbinarized SQM?
* [x] Have you attached your RPT (If the issue relates to data, also attch Server RPT and ALiVE Plugin Log)?
* [ ] Have you attached screenshots of the Parameters set on the offending Module?

### Description

fnc_holdaction error on asym objects like roadblocks and recruitment jobbies

```
15:59:53 Error in expression <radius", _radius] call ALiVE_fnc_Dump;

_result;
};


if (_num > 5) then {_num =>
15:59:53   Error position: <_result;
};


if (_num > 5) then {_num =>
15:59:53   Error Undefined variable in expression: _result
15:59:53 File \x\alive\addons\civ_placement\fnc_createRoadblock.sqf [ALiVE_fnc_createRoadblock], line 1800
15:59:53 Error in expression <_fnc_holdActionAdd", 0,true];
} foreach _roads;
};


[_objective,"roadblocks",[[>
15:59:53   Error position: <_roads;
};


[_objective,"roadblocks",[[>
15:59:53   Error Undefined variable in expression: _roads
15:59:53 File \x\alive\addons\mil_opcom\fnc_INS_helpers.sqf [ALiVE_fnc_INS_helpers], line 2217
```

### Steps to Reproduce

1. Create simple asym mission
2. Approach a roadblock
3. No option to disable with hold actioin

**Expected behavior:** [What you expected to happen]

Hold action to disable

**Actual behavior:** [What actually happened]

Nuffin.

Worth noting that the hold action still works on rescue pilot autotask and other asym objects like Recruitment HQs (didn't test all of them)

[ALiVE_Test_Asym.Stratis.zip](https://github.com/ALiVEOS/ALiVE.OS/files/1523963/ALiVE_Test_Asym.Stratis.zip)

[Arma3_x64_2017-12-02_15-35-44.zip](https://github.com/ALiVEOS/ALiVE.OS/files/1523964/Arma3_x64_2017-12-02_15-35-44.zip)

**Comment by HeroesandvillainsOS** [comment]
Here's a rpt from my time with this repro: https://www.dropbox.com/s/9dq1lq91uzku65y/roadbloack_holdaction.rpt?dl=0

I don't get that message, but I get a shit ton of stuff like this: 21:33:16 Ref to nonnetwork object Agent 0xce602140

My issue with the repro is, after thoroughly checking I'd estimate in the neighborhood of 14 or so roadblock compositions, none of them except for one even spawns the charge model needed for the addaction. I ghosted through them all very thoroughly so unless I'm missing something here, this might be the problem.

One time the charge did spawn, it was on the ground and for a split second, the hold action did appear but it immediately went away and I couldn't get it to come back again.

Depot's (IED factories, Civ recruit, etc) seem fine (as you stated).

**Comment by highhead** [comment]
@HeroesandvillainsOS - "Disable roadblock" is an asymmetric commander feature. If using asymmetric warfare, roadblock locations will be determined and created as part of the asymmetric commanders objectives (be it roadblocks created during runtime or preplaced asymmetric locations). Whereas those strategically used roadblocks can be disabled and removed from the asymmetric warfare and the commanders objectives, the random roadblocks placed by the Civilian Placement module will not have an option to disable as they are also not used by the asymmetric commander. I suggest to use the option "Installations (asymm.)" only instead of the Civilian Placements roadblocks option, as the roadblocks created with this option will carry the disable action.
