### ISSUE TITLE
Something is wrong with OPCOM?

### ISSUE THREAD

**Issue by AngusDLX** [ALiVEOS/ALiVE.OS#525]
### Prerequisites

* [x] Can you reproduce the problem using ALiVE and CBA Only?
* [x] Are you running the latest version of ALiVE ?
* [x] Are you running the latest version of CBA_A3?
* [x] Have you attached an unbinarized SQM?
* [x] Have you attached your RPT (If the issue relates to data, also attch Server RPT and ALiVE Plugin Log)?
* [ ] Have you attached screenshots of the Parameters set on the offending Module?

### Description

What happens is that no matter the number of groups, number of simultaneous attacks ... OPCOM only moves one or two groups at the most and it takes a lot of time to create waypoints for other objectives. First I noticed this in Takistan in insurgency where the independents have control of the map, I left the mission running at dawn and the troops were only in the vicinity at the base. To see if it was not a problem related to CUP, then I tested it on Altis only with ALiVE and CBA. Same result. OPCOM does almost nothing even having multiple groups and objectives available. I also tried to change in the module a faster virtual unit speed to see if it would get some result but nothing too.

Another thing was I noticed that some groups never arrive in the "x" created by OPCOM.

As Heroes said in the forum, there have been re-writes in the latest updates to improve the optimization (the performance improvement was really incredible). Is this what I am reporting is a bug or has OPCOM decision-making really been reduced? A clarification would be welcome! 

It does not seem to happen in older versions of ALiVE.

### Steps to Reproduce
1. Start the mission
2. Open Virtual AI System debug
3. Wait...

**Expected behavior:** OPCOM using more groups moving across the map

**Actual behavior:** OPCOM using few groups, no matter the number of groups or number of objectives

Mission: https://drive.google.com/file/d/1i0kkSJb8qql8XuKEZHgYUdiW4NECByuP/view?usp=sharing

RPT: https://pastebin.com/3KEPpP7P

**Comment by HeroesandvillainsOS** [comment]
Just wanted to clarify since you mentioned my post, that it’s worth looking into due to what I understand the recent changes to involve. I do not know enough about the exact nature of the optimization changes to know whether or not they can cause this issue, or if there’s even an issue at all.

Anyway thanks for the well written out ticket.

**Comment by HeroesandvillainsOS** [comment]
I just ran this mission and I'm thinking a few things may be accounting for your impression groups aren't being sent on attack objectives like they should. The first most obvious thing is that OPF is set to Asymmetric, which I think may account for why they are prioritizing their objectives differently than an Invasion or Occupation Commander. Though note, even with how you have it currently, groups are being sent to X and arriving at X, and handfuls of groups on both sides are definitely moving around the map. Nothing seems obviously broken in my eyes (though I do encourage one of the Devs to double check anyway! That's never a bad idea!).

I do think there is one mistake in this mission that might also account for your impressions that something's wrong, because you have BLU's TAOR set to a marker that doesn't exist. I think is causing them to spawn in the exact same places as OPF on mission start. It's advised to be separating spawns using TAOR's so groups don't spawn on top of each other.

Here is your mission, but with the TAOR markers corrected, with Invasion Commanders only, and with simultaneous attack objectives set to 50: https://www.dropbox.com/s/pln5y22k7ds68r8/ALIVEBUGHUNTINGINSURGENCY.Altis.zip?dl=0

Right away, in my first test, I see BLU send about 8 groups off to various makers. Though note, just because it's set to 10, or 50, I don't think means it has to be 10 (or 50) being sent on attack objectives at ALL TIMES. My understanding is, OPCOM still needs groups held back for defending areas and patrolling. It's up to 10 (or 50).

A dev would have to probably confirm here (I am no expert), but to me nothing seems obviously broken with OPCOM doing a QUICK test. If you want, please look at the edited version I linked above and post back if something still seems off.

**Comment by AngusDLX** [comment]
That's why it went wrong! I used the fast foward to test this mission so everything was so bizarre. I did not know that. Sorry, sorry D:

**Comment by DavisBrown723** [comment]
Reopen if issue persists
