### ISSUE TITLE
AI Comd enhancements

### ISSUE THREAD

**Issue by friznit** [ALiVEOS/ALiVE.OS#6]
A collection of enhancements to the AI Commander to make it more versatile, realistic and immersive.

- [ ] **Coordinated attacks:** as commander I find it disturbing to see motorized vehicles always reach the objective first and far in advance of the infantry.  All groups assigned to take the objective must move at the speed of the slowest group.
- [ ] **Extended decision cycle:** identify potential objective (existing functionality) > recce > strike > assault > hold.  Example: recce with Air or SF group; Strike with Air/Arty/Armour; Assault with Mech Inf; hold with Lt Inf
- [ ] **Flexible group composition:** currently OPCOM always sends 4 randomly selected groups on a task.  It should determine the objective priority + strength and type of enemy by recce then allocate groups to match as closely as possible.
- [ ] **Reinforcements** (not the same as LOGCOM delivering replacement groups): If number of groups attacking an objective falls lower than 50% of enemy groups at the objective, OPCOM orders additional groups to reinforce.  Will need to determine objective priority and maybe a cutoff threshold to avoid a meat grinder effect.

### Some other ideas

- [ ] **Mobile field HQ:** simulated Command Post moving a tactical bound behind lead troops.  Destroying it could reduce the speed of battle casualty replacements by LOGCOM; or slow down the OPCOM decision cycle; or force OPCOM to go defensive.
- [ ] **Battlefield recovery:** use repair vehicles to recover damaged and abandoned vehicles from the battlefield.  Tow back to base and respawn crew.
- [ ] **Battle replen:** setup replens with ammo/fuel trucks near front line to be used by active fighting vehicles.

### New OPCOM stances ideas

- [ ] Impetuous: will advance as fast as possible, regardless of different units speeds, will attempt to capture highest priority objectives at all costs; will use no defensive groups
- [ ] Defensive: prioritises defending currently held friendly objectives. Tries to identify closest/biggest enemy threat and sends forces to nearest objective under threat.
- [ ] Cautious: will advance at pace of slowest unit and try to capture and hold all objectives

**Comment by friznit** [comment]
Draft TDD https://docs.google.com/document/d/1rzKMSavXtN4JQo3iKseAzDWGhiYeAY4tLWLfoG_bThI/edit?usp=sharing

**Comment by 1ncontinentia** [comment]
This list looks incredible! All these features look really well thought out. 

Just another idea (only just joined GitHub so please accept apologies if this isn't the done thing!) but one feature I'd love to see on this list is knowing when to retreat from an objective if facing unsustainable casualties or overwhelming odds. This way you could have true asymmetric warfare with small groups withdrawing from unwinnable battles and falling back to other objectives / areas rather than getting wiped out straight away by larger, better equipped forces. If likelihood of profile battle success also depended on the AI Skill Module setting that would be a cheeky bonus too! 

Could always have an OPCOM "Fanatic" level that disables / controls this feature. Force preservation is a pretty big part of most conflicts so this would be really cool. 

Again, apologies if I've misinterpreted how GitHub works. Just let me know the done thing and I'll do it. Would like to get more involved in ALiVE's development if I can!

**Comment by SpyderBlack723** [comment]
Objective State Flow Graph

![objectivestatesflow](https://cloud.githubusercontent.com/assets/11041331/22767408/a7dc9ccc-ee40-11e6-8343-ab245c0d822d.jpg)

States

    Idle
        Objective is ignored for the current cycle
        
    Recon
        SpecOps and air groups are tasked to recce the objective
        
    Strike
        Objective defenders are weakened with either/both indirect and precision attacks
        
    Attack
        Groups are tasked to assault the objective with intent to capture
        
    Hold
        Objective is under friendly control and will be managed for the cycle
            Patrols originating from the objective
            Base guards
            Lower level module may be attached to simulate objectives with increased fidelity
            
    Defend
        Objective is being threatened by nearby enemy forces capable of reducing the amount of defenders below the set threshold
        
    Retreat
        Objective defenders are under immediate threat from nearby enemy forces who outnumber them at least 2:1
