### ISSUE TITLE
Feature Request: Make Ai spawn for UAV's adjustable

### ISSUE THREAD

**Issue by Tress16** [ALiVEOS/ALiVE.OS#602]
The spawn radius for Ai units is adjustable for helicopter, planes, ... in the virtual ai module (ALiVE_sys_profile). Would be nice if we had this option for UAV's too.

**Comment by Vegas** [comment]
Agree with this completely.

Drones are handled like players (due to AI controller), and therefore spawn everything in as they fly around causing performance issues and issues with active limiters. Players usually fly the damn things into different AOs and waste resources spawning in everything in different towns, cities, etc.

Would be nice to have a spawn radius adjustment specifically for drones so that we can make that distance much shorter than other units.

Excited for all the new revisions coming out soon. Keep up the great work gentlemen. o7

@highhead @tupolov

**Comment by DavisBrown723** [comment]
2a41a292232eb017223c4b00da6675511df373ad

**Comment by DavisBrown723** [comment]
Tested on my end with no issues.
