### ISSUE TITLE
Bug: ACEX Survival is active in ORBAT editor (EDITOR CAN DIE)

### ISSUE THREAD

**Issue by diveyez** [ALiVEOS/ALiVE.OS#628]
This cannot be reproduced without ACE,ACEX and the Survival Features active inside the addon options. When a player is editing in ORBAT editor for an extended period of time, they will eventually need to use food and water to avoid passing out, when they pass out their work in ORBAT editor can become useless due to being unavailable for editing after they pass out.

I would like to request that the ORBAT editor module does not load a living character or disables any external features like that one from ACE/ACEX.

Thank you, and that will be all. Great work as always, love you spyder and friznit.

**Comment by marceldev89** [comment]
It's probably better to disable that functionality in ACE's settings or through a description.ext setting (see https://ace3mod.com/wiki/framework/settings-framework.html#using-the-exported-settings-in-the-mission-descriptionext). I don't think we'll be changing how ORBAT works any time soon-ish. I'll leave it open so that, if someone comes along, is free to pick it up. :smiley:

**Comment by friznit** [comment]
It's a whole lot easier to simply disable ACEX survival in the game options whilst using the ORBATRON, rather than recoding ORBATRON to accommodate a rare use case when a feature from another mod is enabled.
