### ISSUE TITLE
[Feature request] init code for spawned groups in the CQB module

### ISSUE THREAD

**Issue by tyl3r99** [ALiVEOS/ALiVE.OS#730]
### Description

I noticed there is no init code box like there is on the combat support modules (I.e. artillery)

This would be very good for putting things like 
disableAi path or disabling vcom with a group this variable

**Comment by tyl3r99** [comment]
Alternatively tick boxes to disable ai path 
So they stay inside buildings

**Comment by NZF-JDWang** [comment]
I would much prefer an init code box because I absolutely hate disableAI "PATH" on units unless it also has a way to break out. Nothing worse than AI just standing like idiots in a building while players are running around outside. May as well just replace them with auto turrets :joy: 

An init code box would allow us to run either CBA or LAMBs garrison functions which come with the ability for AI to have a random chance on breaking garrison.

**Comment by DarrellJMartin** [comment]
AI Garrison options now implemnted in CQB module
