### ISSUE TITLE
Combat Support: Unable to use Advanced Vehicle Placement

### ISSUE THREAD

**Issue by TheBamse** [ALiVEOS/ALiVE.OS#78]
Arma 3 1.62.137494

Mods loaded:
CBA 3.0.0.160713
ALiVE 1.1.1.1607191

Steps to reproduce:
1. Create new mission on whatever vanilla island.
2. Place player unit, required ALiVE modules, and all the necessary modules for Combat support. Configure to your liking.
3. Place unit meant to be usable as combat support, for example UH80. Sync to combat support module, paste according to wiki in units' init. 
4. try locally or upload to dedicated server, result is the same. Unit will not show up as available combat support. Tested with all types of units ... CAS, Transport and Arty. (A164, UH80 and Scorcher respectively)

I've tried with multiple types of units, configurations, module configurations, mods and so on just for the sake of testing, but since it doesn't work even with vanilla units chances of getting it to work with modded units might be hard :)
Placing the actual transport module or arty module works perfectly as it should (except for issue #71, I'm getting the same thing). Pre-placing arty and transport helicopters to my own liking is just the way I want to do it (if possible) since you can set it up nicely in custom built FOBs for example and still maintain full control over the actual ingame placement.

**Comment by friznit** [comment]
I'm unable to repro.  Using Tanoa map and test with both vanilla (CBA/ALiVE) and a load of addons (ACE, RHS, ASR_AI etc).

1.  Place a unit and a support crate (so I can equip the laser des).
2.  Place ALiVE (Required) & Player Combat Support module
3.  Place a crewed helicopter (I'm using RHS UH-60M)
4.  Heli init line `this setvariable ["CS_TYPE","TRANSPORT"]; this setvariable ["CS_CALLSIGN","Manual Tpt Test"];`
5.  Sync heli to module

Works both locally and on dedi server.  Tested with module and manually placed CAS for planes and helis, and same for artillery.  Tested with Virtual AI module on both settings (all and synced only).  Tested with and without C2ISTAR module placed.

The only issue I can find is a known bug with sling loading which has been fixed in dev.

**Comment by TheBamse** [comment]
Excluding units from profiling worked perfectly. Thanks for an awesome reply and sorry for not trying that out.

**Comment by friznit** [comment]
No probs!  Glad it works for you.  Have fun blowing the crap out of things :)
