### ISSUE TITLE
Armour Types in the Virtual Simulation are extremely overpowered 

### ISSUE THREAD

**Issue by Azraeel** [ALiVEOS/ALiVE.OS#792]
### Prerequisites

* [X] Can you reproduce the problem using ALiVE and CBA Only?
* [X] Are you running the latest version of ALiVE ?
* [X] Are you running the latest version of CBA_A3

### Description
Profile Simulator does not account for AT Capabilites within Infantry and other none Armour Types causing Armour to be extremely overpowered in Virtual Combat due to them having the most up and firepower.

https://github.com/ALiVEOS/ALiVE.OS/blob/42fa6946b558c2ba77428e9bd27d613193839cb0/addons/sys_profile/fnc_profileSimulator.sqf#L756
 ^ can see its fairly explained

**Expected behavior:** [What you expected to happen]
I expect AT Capable units to actually be able to produce more damage onto Armour Units

**Actual behavior:** [What actually happened]
This is not the really as they produce the same dmg outputs as if AT does not exist

**Comment by DavisBrown723** [comment]
This is only kind-of correct. ALiVE doesn't keep track of what weapons each unit is carrying.. this simply isn't feasible performance wise. The possibility for infantry profiles to inflict "AT" damage to vehicles is simulated though... otherwise infantry would never be able to kill an armor vehicle.
